export const EUROPEANCOUNTRIES = [
    "Albánsko",
    "Andorra",
    "Arménsko",
    "Azerbajdžan",
    "Belgicko",
    "Bielorusko",
    "Bosna a Hercegovina",
    "Bulharsko",
    "Česko",
    "Čierna Hora",
    "Dánsko",
    "Estónsko",
    "Fínsko",
    "Francúzsko",
    "Grécko",
    "Gruzínsko",
    "Holandsko",
    "Chorvátsko",
    "Írsko",
    "Island",
    "Kazachstan",
    "Kosovo",
    "Lichtenštajnsko",
    "Litva",
    "Lotyšsko",
    "Luxembursko",
    "Maďarsko",
    "Malta",
    "Moldavsko",
    "Monako",
    "Nemecko",
    "Nórsko",
    "Poľsko",
    "Portugalsko",
    "Rakúsko",
    "Rumunsko",
    "Rusko",
    "San Maríno",
    "Severné Macedónsko",
    "Slovensko",
    "Slovinsko",
    "Srbsko",
    "Španielsko",
    "Švajčiarsko",
    "Švédsko",
    "Taliansko",
    "Ukrajina",
    "Vatikán",
    "Veľká Británia"
];
