export const PROCESS = [
    "RAW_MATERIAL_COLLECTION",
    "RAW_MATERIAL_PROCESS",
    "COMPONENT",
    "PACKAGING_MATERIAL",
    "PACKAGING",
    "OEM_MANUFACTURING",
    "OEM_PROCESSING",
    "DISTRIBUTOR",
    "WAREHOUSE"
]