<?php

declare(strict_types=1);

namespace App\Enums\Nodes;

enum ProcessType: string
{
    case SUPPLIER_OF_RAW_MATERIAL = 'SUPPLIER_OF_RAW_MATERIAL';
    case SUPPLIER_OF_PROCESSED_RAW_MATERIAL = 'SUPPLIER_OF_PROCESSED_RAW_MATERIAL';
    case SUPPLIER_OF_COMPONENTS = 'SUPPLIER_OF_COMPONENTS';
    case SUPPLIER_OF_PACKAGING_MATERIAL = 'SUPPLIER_OF_PACKAGING_MATERIAL';
    case SUPPLIER_OF_PACKAGING = 'SUPPLIER_OF_PACKAGING';
    case OEM_MANUFACTURING = 'OEM_MANUFACTURING';
    case OEM_ASSEMBLY = 'OEM_ASSEMBLY';
    case OEM_PROCESS = 'OEM_PROCESS';
    case DISTRIBUTOR = 'DISTRIBUTOR';
    case WAREHOUSE = 'WAREHOUSE';
}
