version: '3.3'

services:
  nuxt:
    build:
      context: ./app
    image: nuxt_dev
    container_name: nuxt_dev
    command: npm run dev
    volumes:
    - ./app:/app
    - /app/node_modules
    ports:
      - "3000:3000"
      - "24678:24678"